#!/bin/sh
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64
echo "Waiting 1 seconds..."
sleep 1
#exec env LD_LIBRARY_PATH=/usr/local/frc/lib java -jar java-multiCameraServer-all.jar
cd frcvision
exec bin/frcvision
